---

- name: Remove all persistent Dock applications
  shell: dockutil --remove all

- name: Set persistent Dock applications (user)
  shell: dockutil --add '/Applications/{{ item }}.app'
  with_items:
    - Path Finder
    - Google Chrome
    - Slack
    - Telegram Desktop
    - Kiwi for Gmail
    - Calendar
    - Dash
    - Spotify
    - nvALT
    - iTerm
  ignore_errors: true
