---

- name: Remove all persistent Dock applications
  shell: dockutil --remove all

- name: Set persistent Dock applications (user)
  shell: dockutil --add "{{ item }}"
  with_items:
    - '/Applications/Telegram.app'
    - '/Applications/Google Chrome.app'
    - '/Applications/Slack.app'
    - '/Applications/Kiwi for Gmail.app'
    - '/System/Applications/Calendar.app'
    - '/Applications/Remember The Milk.app'
    - '/Applications/Dash.app'
    - '/Applications/iTerm.app'
    - '/Applications/Spotify.app'
    - '/Applications/nvALT.app'
    - '/Applications/Paprika Recipe Manager 3.app'
    - '/Applications/Microsoft Outlook.app'
  ignore_errors: true
