---

- name: Install completion formulas with Homebrew
  homebrew: name={{ item }}-completion state=latest
  with_items:
    - bundler
    - gem
    - pip
    - rake
    - ruby
    - tmuxinator
    - vagrant
