---

- name: Get Homebrew path
  shell: brew --prefix
  register: homebrew_path
  changed_when: false

- name: Ensure Homebrew permissions
  file: path={{ homebrew_path.stdout }} state=directory owner={{ ansible_ssh_user }} recurse=yes
  sudo: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install Homebrew taps
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/dupes
    - homebrew/versions
    - caskroom/cask
    - caskroom/versions

- name: Install Homebrew Cask brew
  homebrew: name=brew-cask state=latest

- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - the_silver_searcher
    - grep
    - autojump
    - curl
    - wget
    - bash
    - coreutils
    - ctags
    - cmake
    - dockutil
    - elinks
    - git
    - gh
    - gnu-getopt
    - htop-osx
    - go
    - hping
    - httperf
    - httpry
    - hub
    - iftop
    - ngrep
    - json-c
    - libpng
    - mackup
    - mercurial
    - mtr
    - mosh
    - pcre
    - phantomjs
    - pigz
    - psgrep
    - readline
    - reattach-to-user-namespace
    - rename
    - qt
    - s3cmd
    - tig
    - tmux
    - tree
    - watch
    - weechat
    - wrk
