---
- name: Install homebrew completions tap
  homebrew_tap: name=homebrew/completions state=present

- name: Install completion formulas with Homebrew
  homebrew: name={{ item }}-completion state=latest
  with_items:
    - bundler
    - gem
    - pip
    - rake
    - ruby
    - tmuxinator
    - vagrant
