---
- name: Install homebrew fonts tap
  homebrew_tap: name=caskroom/fonts state=present

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install fonts with Homebrew Cask
  homebrew_cask: name=font-{{ item }} state=present
  with_items:
    - source-code-pro
    - sauce-code-powerline
    - anonymous-pro-for-powerline
    - droid-sans-mono-for-powerline
    - inconsolata-for-powerline
    - meslo-lg-for-powerline
    - ubuntu-mono-powerline
