---

- name: Install Cask apps
  homebrew_cask: name={{ item }} state=present
  with_items:

    # main dev apps
    - adium
    - sourcetree
    - tunnelblick
    - slack
    - google-chrome
    - firefox
    - iterm2
    - virtualbox
    - vagrant
    - vagrant-manager
    - virtualbox
    - the-unarchiver

    # quicklook plugins
    - qlcolorcode
    - qlmarkdown
    - quicklook-json
    - qlstephen
    - qlvideo

    # personal apps
    - path-finder
    - dropbox
    - google-drive
    - utorrent
    - vlc
    - flux
    - spotify
    - spotify-notifications
    - android-file-transfer
    - handbrake
    - send-to-kindle
    - nvalt
    - karabiner
    - bettertouchtool
    - caffeine
    - crashplan

    # paid apps
    - bartender
    - daisydisk
    - istat-menus4

- name: Install Alfred app
  homebrew_cask: name=alfred state=present
  register: alfred_install

- name: Link Homebrew folders into Alfred
  command: brew cask alfred link
  when: alfred_install|changed
