---
- name: Install homebrew fonts tap
  homebrew_tap: name=homebrew/cask-fonts state=present

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install fonts with Homebrew Cask
  homebrew: name=font-{{ item }} state=present
  with_items:
    - source-code-pro
    - source-code-pro-for-powerline
    - anonymice-powerline
    - droid-sans-mono-for-powerline
    - inconsolata-for-powerline
    - meslo-for-powerline
    - ubuntu-mono-derivative-powerline
