---

- name: Get Homebrew path
  shell: brew --prefix
  register: homebrew_path
  changed_when: false

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - bash
    - bash-completion
    - cmake
    - coreutils
    - ctags
    - curl
    - diffutils
    - dockutil
    - elinks
    - fasd
    - fontconfig
    - freetype
    - git
    - gnu-getopt
    - gnutls
    - go
    - grep
    - highlight
    - hping
    - htop-osx
    - httperf
    - httpry
    - hub
    - iftop
    - jq
    - json-c
    - leiningen
    - less
    - bat
    - delta
    - mercurial
    - moreutils
    - mtr
    - ngrep
    - nmap
    - pcre
    - pigz
    - psgrep
    - ranger
    - readline
    - rename
    - scrypt
    - shellcheck
    - the_silver_searcher
    - tig
    - tmux
    - tree
    - watch
    - wget
