---

- name: Install Cask apps
  homebrew_cask: name={{ item }} state=present
  with_items:

    # main dev apps
    - dash
    - tunnelblick
    - slack
    - google-chrome
    - postman
    - firefox
    - iterm2
    - virtualbox # requires some permissions at the OS level
    - vagrant
    - vagrant-manager
    - the-unarchiver
    - lastpass
    - wkhtmltopdf

    # quicklook plugins
    - syntax-highlight
    - qlstephen
    - qlvideo

    # personal apps
    - dropbox
    - vlc
    - flux
    - spotify
    - spotify-notifications
    - handbrake
    - nvalt
    - caffeine
    - telegram
    - calibre
    - android-messages
    - remember-the-milk
    - kindle
    - send-to-kindle
    - xbar
    - transmission
    - plex-media-server
    - notion

    # paid apps
    - bartender
    - daisydisk
    - istat-menus
    - alfred
    - little-snitch
    - micro-snitch

    # work
    - microsoft-outlook
    - microsoft-excel
