---

- name: Install Homebrew AdoptOpenJDK Java tap
  homebrew_tap: name="AdoptOpenJDK/openjdk" state=present

- name: Install Java versions
  shell: brew install {{ item.package }}
  register: brew_install
  changed_when: "'already installed' not in brew_install.stderr"
  with_items: java_versions

- name: Install scala
  homebrew: name={{ item }} state=latest
  with_items:
    - scala
    - sbt

- name: Get jenv Java version manager
  git: repo="https://github.com/jenv/jenv.git" dest="{{ jenv_directory }}" version="{{ jenv_version }}"
  tags:
    - jenv

- name: Enable jenv export plugin
  shell: "{{ jenv_setup_command }} && jenv enable-plugin export"
  args:
    executable: /bin/bash
  tags:
    - jenv

- name: Add Java versions to jenv
  shell: "{{ jenv_setup_command }} && jenv add $(/usr/libexec/java_home -v {{ item.version }}) && jenv rehash"
  with_items: java_versions
  args:
    executable: /bin/bash
  tags:
    - jenv
