---

- name: Clone NVM repo
  git: repo="https://github.com/nvm-sh/nvm.git" dest="{{ nvm_directory }}" update=no

- name: Figure out latest released NVM tag
  shell: git describe --abbrev=0 --tags --match "v[0-9]*" origin
  args:
    chdir: "{{ nvm_directory }}"
  register: git_nvm_tag
  changed_when: false

- name: Check out latest NVM tag
  git: repo="https://github.com/nvm-sh/nvm.git" dest="{{ nvm_directory }}" version="{{ git_nvm_tag.stdout }}"

- name: Install node.js
  shell: "{{ nvm_env_setup_command }} && nvm install {{ global_nodejs_version }} && nvm alias default {{ global_nodejs_version }}"
