---

- name: Install Ruby gems
  shell: gem install {{ item }} --user-install --no-document --no-force --conservative
  register: gem_install
  changed_when: gem_install.stdout | length > 0
  with_items:
    - tmuxinator
    - bropages
    - tugboat
