---

- name: Install Ruby and related with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - rbenv
    - ruby-build
    - rbenv-vars
    - rbenv-default-gems

- name: Check installed Ruby version
  shell: rbenv versions
  register: rbenv_versions
  changed_when: false

- name: Install Ruby version
  shell: rbenv install -s {{ global_ruby_version }}
  when: rbenv_versions.stdout.find('{{ global_ruby_version }}') == -1
  register: ruby_install

- name: Set global Ruby version
  shell: rbenv global {{ global_ruby_version }}
  when: ruby_install|changed

- name: Update gem system
  shell: gem update --system
  when: ruby_install|changed

- name: Check if Bundler installed
  shell: gem list
  register: installed_gems
  changed_when: false

- name: Install bundler
  shell: gem install bundler --no-document && rbenv rehash
  when: installed_gems.stdout.find('bundler') == -1

- name: Configure Bundler for parallel execution
  shell: bundle config --global jobs {{ ansible_processor_cores }} creates=~/.bundle/config
