---

- name: Install software updates
  shell: softwareupdate --install --all 2>&1
  register: update_command
  changed_when: "'No updates are available' not in update_command.stdout"

- name: Re-agree to xcode terms
  shell: xcodebuild -license accept 2>&1
  sudo: true
  register: xcode_terms_command
  changed_when: xcode_terms_command.stdout != ""

- debug: xcode_terms_command
  when: xcode_terms_command.stdout != ""
