---

- name: Clone dotfiles repository
  git: repo=https://github.com/jshafton/dotfiles_new dest=~/.dotfiles
  register: dotfiles_clone_result

- name: Run dotfiles installer
  shell: ./install chdir=~/.dotfiles
  when: dotfiles_clone_result|changed
