---

- name: Install Homebrew Cask brew
  homebrew: name=brew-cask state=latest

- name: Install Cask apps
  homebrew_cask: name={{ item }} state=present
  with_items:

    # main dev apps
    - adium
    - sourcetree
    - tunnelblick
    - wkhtmltopdf
    - slack
    - cord
    - google-chrome
    - iterm2
    - macvim
    - sublime-text
    - virtualbox
    - vagrant
    - vagrant-manager
    - virtualbox
    - the-unarchiver

    # quicklook plugins
    - qlcolorcode
    - qlmarkdown
    - quicklook-json
    - qlstephen
    - qlvideo

    # personal apps
    - dropbox
    - utorrent
    - vlc
    - flux
    - spotify
    - android-file-transfer
    - handbrake
    - send-to-kindle
    - nvalt
    - karabiner
    - bettertouchtool

    # Site is currently down
    # - caffeine

    # paid apps
    - bartender
    - daisydisk
    - istat-menus4
    - adobe-photoshop-lightroom

- name: Install Alfred app
  homebrew_cask: name=alfred state=present
  register: alfred_install

- name: Link Homebrew folders into Alfred
  command: brew cask alfred link
  when: alfred_install|changed
